### ISSUE TITLE
URP Outline_Color shader adaptation

### ISSUE THREAD

**Issue by clearskystudio** [ExtendRealityLtd/Tilia.Utilities.Shaders.Unity#5]
Oculus Quest works with URP only and it'd be super awesome to have a working outline shader for this scenario in VRTK 4 out-of-the-box.

**Comment by thestonefox** [comment]
This ticket is largely related to https://github.com/ExtendRealityLtd/Tilia.Utilities.Shaders.Unity/issues/6
